Pivot Tables and crosstabs

In [2]:
import numpy as np
import pandas as pd

Pivot Table
in pivot table we use aggrergate functions

In [6]:
data = {
    'Date': pd.date_range('2023-01-01',periods = 20),
    'Product': ['A','B','C','D'] *5,
    'Region': ['East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10,100,20),
    'Rep':['John','Mary','Bob','Alice','John','Mary','Bob','Alice','John','Mary',
           'Bob','Alice','John','Mary','Bob','Alice','John','Mary','Bob','Alice']
}


df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] ='Q' +df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    950     16   John  January      Q1
1  2023-01-02       B   West    532     98   Mary  January      Q1
2  2023-01-03       C  North    631     80    Bob  January      Q1
3  2023-01-04       D  South    440     45  Alice  January      Q1
4  2023-01-05       A   East    248     97   John  January      Q1
5  2023-01-06       B   West    890     27   Mary  January      Q1
6  2023-01-07       C  North    640     37    Bob  January      Q1
7  2023-01-08       D  South    534     81  Alice  January      Q1
8  2023-01-09       A   East    394     48   John  January      Q1
9  2023-01-10       B   West    784     56   Mary  January      Q1
10 2023-01-11       C  North    963     77    Bob  January      Q1
11 2023-01-12       D  South    234     45  Alice  January      Q1
12 2023-01-13       A   East    807     48   John  January      Q1
13 2023-01-14       B   West    471     60   Mary  January      Q1
14 2023-01-15       C  North    700     93    Bob  January      Q1
15 2023-01-16       D  South    457     75  Alice  January      Q1
16 2023-01-17       A   East    320     85   John  January      Q1
17 2023-01-18       B   West    552     28   Mary  January      Q1
18 2023-01-19       C  North    344     83    Bob  January      Q1
19 2023-01-20       D  South    697     78  Alice  January      Q1

In [9]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product')#bydefault mean productwise

Product      A      B      C      D
Region
East     543.8    NaN    NaN    NaN
North      NaN    NaN  655.6    NaN
South      NaN    NaN    NaN  472.4
West       NaN  645.8    NaN    NaN

In [12]:
#use case of this is in Heat Map
pd.pivot_table(df,values = 'Sales',index='Region',columns='Product',aggfunc='median') #median productwise(can be any aggregate func)

Product      A      B      C      D
Region
East     394.0    NaN    NaN    NaN
North      NaN    NaN  640.0    NaN
South      NaN    NaN    NaN  457.0
West       NaN  552.0    NaN    NaN

In [14]:
#for multiple columns
pivot2 = pd.pivot_table(df, values =['Sales','Units'],index='Region',columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     543.8    NaN    NaN    NaN  58.8   NaN   NaN   NaN
North      NaN    NaN  655.6    NaN   NaN   NaN  74.0   NaN
South      NaN    NaN    NaN  472.4   NaN   NaN   NaN  64.8
West       NaN  645.8    NaN    NaN   NaN  53.8   NaN   NaN

Cross Tabs 
in cross tab we use counting functions

In [16]:
pd.crosstab(df['Region'],df['Product'])# here counts come unlike aggregate functions which were used in the pivot table

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0