In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r"Countries.csv")

In [3]:
dataset.head(5)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [4]:
dataset.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

Solve the following questions

In [7]:
#which country has the highest population
dataset[dataset["population"] == dataset["population"].max()]["country"]

75    India
Name: country, dtype: object

In [8]:
#what is the capital of the country with highest population
dataset[dataset["population"] == dataset["population"].max()][["country","capital_city"]]

   country capital_city
75   India    New Delhi

In [11]:
#which country has the least population
dataset[dataset["population"] == dataset["population"].min()][["country","population"]]

    country  population
179  Tuvalu       11312

In [12]:
#What is the capital of the country with the least population
dataset[dataset["population"] == dataset["population"].min()][["country","capital_city","population"]]

    country capital_city  population
179  Tuvalu     Funafuti       11312

In [16]:
#give me the top 5 countries with highest democratic score
dataset.sort_values(by='democracy_score',ascending = False).head(5)[["country","democracy_score"]]

         country  democracy_score
127       Norway             9.87
74       Iceland             9.58
164       Sweden             9.39
122  New Zealand             9.26
46       Denmark             9.22

In [22]:
#how many total regions are there
dataset['region'].value_counts().count()

np.int64(22)

In [32]:
# how many countries lie in Eastern Europe region
dataset[dataset['region'] == 'Eastern Europe']['country']

14             Belarus
24            Bulgaria
43      Czech Republic
73             Hungary
111            Moldova
136             Poland
139            Romania
140             Russia
151    Slovak Republic
181            Ukraine
Name: country, dtype: object

In [34]:
#Who is the political leader of the second highest populated country method a
dataset.sort_values(by='population', ascending = False).iloc[1]['political_leader']

'Xi Jinping'

In [35]:
#who is the political leader of the second highest populated country method b
dataset[dataset["population"] == dataset["population"].nlargest(2).iloc[1]]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
34,China,People's Republic of China,Chinese yuan,Beijing,Eastern Asia,Asia,Chinese,35.0,105.0,5285080.0,...,1412175000,24.9412,514596570,897578430,0.99,3.32,Authoritarian,34.5,Xi Jinping,General Secretary of the Communist Party

In [42]:
#how many countries are there whose political leaders are unknown
dataset[dataset['political_leader'].isna()]['country'].count()

np.int64(7)

In [44]:
#how many country have republica in their full name
count = 0
def counting(txt):
    global count
    if 'republic' in txt.lower():
        count +=1
    return txt
dataset["country_long"] = dataset['country_long'].apply(counting)
print(count)

125

In [46]:
#which country in africa has highest population
africa_df = dataset[dataset['continent'] == 'Africa']

In [48]:
africa_df[africa_df['population'] == africa_df['population'].max()]['country']

125    Nigeria
Name: country, dtype: object